### PR TITLE
fix #8

### LINKED ISSUE #8: AHKPY immediately terminates without error
I use this module on three Windows machines and it worked flawlessly. It's an awesome tool, thank you for developing it.

A couple of days ago I decided to migrate one of the machines to a proper python environment. I'm usually not working on the machine and didn't spend the time to setup python properly, initially.

I uninstalled the system python, and installed python `3.10.2` using `pyenv`. The other machines are running the same python version and are running fine. I then installed other modules and did not experience any kind of trouble until I attempted to run 2 of my scripts via `python -m ahkpy script.py`:

This command returns an empty line and terminates immediately. No error, no logs. Same effect when I call `python -m ahkpy -h`. Any idea how I could debug the problem without cloning this repo and doing the `pip install -e .` shenanigans?

I did:
- run from both elevated and non-elevated terminals
- uninstall and check if the import is still working; it is not
- reinstall `autohotkey.py`
- make sure it was installed for the correct python version I even installed it using `python -m pip install autohotkey.py`
- triple check it's running on the correct pyenv python executable
- successfully `import ahkpy` from within the interpreter; no import errors
- run two scripts that work on other machines and are located in different directories; no namespace conflicts
- check if AutoHotkey.exe is working properly; also checked if there were python / ahk processes running in the background and terminated them all
- reboot / restart terminal sessions
- check system path and removed the old system python paths (even renamed them to make sure it's not importing from the old folder)
- run a script directly using `python script.py` and I correctly receive the `RuntimeError: AHK interop is not available. Please start your code as 'py -m ahkpy main.py'.`

I am not using `virtualenv`.

Locations:
```
    c:\users\tommi\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages\ahkpy\*
    c:\users\tommi\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages\autohotkey.py-0.1.2.dist-info\*
    c:\users\tommi\.pyenv\pyenv-win\versions\3.10.2\scripts\ahkpy.exe

    $ pyenv which python
    C:\Users\Tommi\.pyenv\pyenv-win\versions\3.10.2\python.exe
    
    $ pyenv which pip
    C:\Users\Tommi\.pyenv\pyenv-win\versions\3.10.2\Scripts\pip.exe
```

Any idea what I am missing and how to debug the situation? Thank you for your time!

### PR DESCRIPTION
**Pull request by MarcWeber**
If this gets fixed pip install should be fine again without post-patching.

### CODE REVIEW

**Comment by Perlence** [comment]
Hey @MarcWeber, could you please summarize the problem this PR solves and what the steps are to reproduce it? I have a feeling that it may not be related to the original issue that Thomas raised in #8.

**Comment by MarcWeber** [comment]
Sure. I had the same experience. And the cause was that some Python based encoding imports failed.
The fix was to set the pythonpath before starting the interpreter.

So I had the strong feeling that I experienced the same issue.
And I was glad to get the helpful information about how to make the errors visible.
And that showed me the problem.

The fix is temporary because the Set_Path will go away.
But I didn't have the nerves to go through the hassle finding out
how to build proper initialization structures.

So I could reproduce and track the issue. And after those patches my script started working.

And I got my script down from 200 to 60 lines or so.
So loving this code already :)

**Comment by Perlence** [comment]
Thank you for your kind words and contribution!

Do you happen to know why you started getting the `No module named 'encodings'` error? I'd like to reproduce it locally to see how the fix works. For example, how did you install Python, do you use a virtual environment?

**Comment by MarcWeber** [comment]
1) get miniconda
2) conda create -n name
3) conda activate name
4) install something like opencv (im.read or so + showing it should be enough)
5) import the module setting up some hooks
try and you'll get encodings something not found failing exactly at Py_Initialize() so no chance to set sys.path at any other stage.

The problem happens on Windows obviously.
You can get miniconda from here: https://docs.conda.io/en/latest/miniconda.html

**Comment by Perlence** [comment]
Awesome, thanks! Let me try it. I assume you did `pip install autohotkey.py` some time after activating the Conda environment?

**Comment by Perlence** [comment]
Hey @MarcWeber, could you please pull the latest changes from the master branch and see if they fix the issue for you? If they do, I'll close this PR, but thanks for taking the time to improve the project!

The issue with `Py_SetPath` is that it breaks Tkinter. I switched to `PySys_SetPath` in 1f5d8562dccd32d1d9062f7968cec6fd707329b5, so that's where we started from.

**Comment by Perlence** [comment]
I'll go ahead and close this one.

**Pull request closed without merging**
